name: speed_staff_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.1
  shared_preferences: ^2.5.4
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^9.2.1
  easy_localization: ^3.0.8
  toastification: ^3.0.3
  gap: ^3.0.1
  url_launcher: ^6.3.2
  dartz: ^0.10.1
  connectivity_plus: ^7.0.0
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/

  
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito/Nunito-MediumItalic.ttf
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
